% 定义真实类别和预测类别
trueLabels = [repmat({'C_glabrata'}, 14, 1); ...
              repmat({'C_albicans'}, 13, 1); ...
              repmat({'C_tropicalis'}, 3, 1); ...
              repmat({'A_flavus'}, 3, 1); ...
              repmat({'Penicillium'}, 2, 1); ...
              repmat({'Fusarium'}, 2, 1); ...
              repmat({'A_terreus'}, 1, 1)];

predictedLabels = [repmat({'C_glabrata'}, 13, 1); {'Other'}; ...
                   repmat({'C_albicans'}, 13, 1); ...
                   repmat({'C_tropicalis'}, 3, 1); ...
                   repmat({'A_flavus'}, 3, 1); ...
                   repmat({'Penicillium'}, 2, 1); ...
                   repmat({'Fusarium'}, 2, 1); ...
                   repmat({'A_terreus'}, 1, 1)];

% 定义类别
categories = {'C_glabrata', 'C_albicans', 'C_tropicalis', ...
              'A_flavus', 'Penicillium', 'Fusarium', 'A_terreus', 'Other'};

% 将字符型标签转换为分类数组
trueLabelsCategorical = categorical(trueLabels, categories);
predictedLabelsCategorical = categorical(predictedLabels, categories);

% 绘制混淆矩阵
figure;
plotconfusion(trueLabelsCategorical, predictedLabelsCategorical);

% 获取混淆矩阵数据
confMat = confusionmat(trueLabels, predictedLabels, 'Order', categories);
totalSamples = sum(confMat, 'all'); % 总样本数
correctIdentifications = sum(diag(confMat)); % 正确识别数
overallAccuracy = (correctIdentifications / totalSamples) * 100; % 总体准确率

% 获取图像对象并自定义标题
ax = gca; % 获取当前轴
ax.Title.String = ['Confusion Matrix for Fungal Identification', newline, ...
                   'Overall Accuracy: ', num2str(overallAccuracy, '%.2f'), '%'];
ax.FontSize = 12; % 设置字体大小
%colorbar